### ISSUE TITLE
Module Missing Error

### ISSUE THREAD

**Issue by PankajMishra1977** [Ibro/SignalRSimpleChat#2]
On ng serve command, I got an exception that...

module.js:471
    throw err;
    ^

Error: Cannot find module 'angular-devkit/core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Downloads\SignalRSimpleChat-asp-net-core-angular\SignalRSimpleChat-asp-net-core-angular\AngularAspNetCoreSi
gnalR.Angular\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Ibro** [comment]
Hey @PankajMishra1977 
Thanks for reporting this. I have updated Angular related bits. It should work now:

1. Pull latest
2. Delete _node_modules_ folder
3. `npm install`
